# Generated by Django 4.1.7 on 2023-04-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KODBURG', '0003_room_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notice',
            field=models.ManyToManyField(blank=True, to='KODBURG.notice'),
        ),
    ]
