# Generated by Django 4.1.7 on 2023-04-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("KODBURG", "0005_user_descriptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chats",
            field=models.ManyToManyField(blank=True, to="KODBURG.room"),
        ),
    ]
