# Generated by Django 4.1.7 on 2023-04-30 21:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("KODBURG", "0007_user_connected"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="connected",
        ),
        migrations.AddField(
            model_name="user",
            name="connected_from",
            field=models.ManyToManyField(
                blank=True, related_name="connect_from", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="connected_to",
            field=models.ManyToManyField(
                blank=True, related_name="connect_to", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
