# Generated by Django 4.1.7 on 2023-04-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "KODBURG",
            "0009_remove_user_connected_from_remove_user_connected_to_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="requests",
            name="onl_from",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name="requests",
            name="onl_to",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
