# Generated by Django 4.1.7 on 2023-05-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("KODBURG", "0012_remove_requests_onl_from_remove_requests_onl_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="mes",
            field=models.ManyToManyField(
                blank=True, related_name="mes", to="KODBURG.messages"
            ),
        ),
    ]
