# Generated by Django 4.1.7 on 2023-05-19 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("KODBURG", "0013_room_mes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="usernameFrom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usernameFrom",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="usernameTo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usernameTo",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
