# Generated by Django 4.1.7 on 2023-05-19 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("KODBURG", "0014_alter_notice_usernamefrom_alter_notice_usernameto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="user_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_from",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
