# Generated by Django 4.1.7 on 2023-05-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("KODBURG", "0015_alter_messages_user_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="new_messages",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
