# Generated by Django 4.1.7 on 2023-05-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("KODBURG", "0016_user_new_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_confirm",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
