# Generated by Django 4.1.7 on 2023-05-27 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("KODBURG", "0017_user_email_confirm"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_hash",
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="chats",
            field=models.ManyToManyField(
                blank=True, to="KODBURG.room", verbose_name="Переписки"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="connections",
            field=models.ManyToManyField(
                blank=True,
                related_name="connections",
                to="KODBURG.requests",
                verbose_name="Связи",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="descriptions",
            field=models.ManyToManyField(
                blank=True,
                related_name="Descriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Подписки",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="friends",
            field=models.ManyToManyField(
                blank=True, to=settings.AUTH_USER_MODEL, verbose_name="Друзья"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="notice",
            field=models.ManyToManyField(
                blank=True, to="KODBURG.notice", verbose_name="Уведомления"
            ),
        ),
    ]
