# Generated by Django 4.1.7 on 2023-05-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("KODBURG", "0018_user_email_hash_alter_user_chats_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_hash",
            field=models.CharField(blank=True, default="", max_length=10000, null=True),
        ),
    ]
