# Generated by Django 4.1.7 on 2023-05-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("KODBURG", "0019_alter_user_email_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_hash",
            field=models.CharField(blank=True, default="", max_length=10000, null=True),
        ),
    ]
