# Generated by Django 4.1.7 on 2023-03-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KODBURG', '0002_rename_message_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='time_create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
