# Generated by Django 4.1.7 on 2023-04-09 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("KODBURG", "0006_user_chats"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="connected",
            field=models.ManyToManyField(
                blank=True, related_name="connect", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
